previews:
  generation: automatic

services:
  # Backend service
  - type: web
    name: backend
    runtime: docker
    dockerContext: ./backend
    dockerfilePath: Dockerfile
    autoDeploy: true # Optional: Automatically deploy on new commits

  # Frontend service
  - type: web
    name: frontend
    runtime: docker
    dockerContext: ./frontend
    dockerfilePath: Dockerfile
    autoDeploy: true # Optional: Automatically deploy on new commits
